services:
  db:
    container_name: postgresBYD
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pcshop
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - app:/data/postgresBYD

  redis:
    container_name: redisBYD
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - app:/data/redisBYD
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  app: