# Generated by Django 5.1.1 on 2024-09-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="basket",
            managers=[],
        ),
    ]
