# Generated by Django 5.1.1 on 2024-10-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("basket", "0002_alter_basket_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basket",
            options={
                "ordering": ["id"],
                "verbose_name": "Basket",
                "verbose_name_plural": "Baskets",
            },
        ),
    ]
