# Generated by Django 5.1.1 on 2024-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Адрес доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="requires_delivery",
            field=models.BooleanField(default=False, verbose_name="Требуется доставка"),
        ),
    ]
