# Generated by Django 5.1.1 on 2024-09-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_delivery_address_alter_order_requires_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Адрес доставки"
            ),
        ),
    ]
